config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  resources :roles
  devise_for :users

  resources :employees
  
  #gives route for import func
  resources :workers do
    collection { post :import }
  end
  
  resources :companies do
    resources :employees
  end
  
  resources :companies do
    resources :workers, controller: 'companies/workers'
  end
  
  get 'home/index'
  
  root to: 'home#index'
  
  resources :salaries

  resources :workers do
    resources :payslips

  end
  
  get '/payslips', to: 'payslips#index', as: :payslips
  post '/payslips/multiple', to: 'payslips#show_multiple', as: :payslips_multiple
  get '/payslips/multiple', to: 'payslips#show_multiple', as: :payslips_export_csv
   

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
    has_many :workers, dependent: :destroy
    has_many :departments, :inverse_of => :company
    has_many :employments, through: :workers
    has_many :paychecks, through: :workers
    
    accepts_nested_attributes_for :workers, reject_if: all.blank?,
                                allow_destroy: true
    
end

app/models/worker.rb
class Worker < ApplicationRecord
    belongs_to :company, optional: true
    has_many :employments
    has_many :salaries
    
    validates :first_name, presence: true
    validates :last_name, presence: true
    #validates :starting_salary, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}
    #validates :pay_rate, presence: true, numericality: {greater_than_or_equal_to: 0.0, less_than_or_equal_to: 1.0}
    
    def full_name
        "#{first_name}, #{last_name}"
    end
    
    def self.import(file)
        #process CSV import for workers
        CSV.foreach(file.path, headers:true) do |row|
            Worker.create! row.to_hash
        end
    end
    
    def convert_rate_pct_to_dec
        self.pay_rate = self.pay_rate.to_f/100 if percentage?
    end
    
    def percentage?
    # returns a true or false
        (self.pay_rate.to_s.include?('%')) or (self.pay_rate.to_f > 1.0)
    end
    
    
end

app/controllers/companies/workers_controller.rb
module Companies

#disregard index,show and destroy method in routes since we in context of a client

    class WorkersController < ApplicationController
    
        def index
            @workers = Worker.all
        end
        
       def show
            @company = Company.find(params[:company_id])
            @worker = worker.find(params[:worker_id])
            @worker.company = @company
        end
        
        def new
            @company = Company.find(params[:company_id])
            @worker = Worker.new
        end
        
        def create
            @worker = Worker.new(worker_params)
            @company = Company.find(params[:company_id])
            @worker.company = @company
            
            
            if @worker.save(worker_params)
                redirect_to worker_path(@worker.id)
            else
                render 'new'
            end
            
        end
        
        def edit
            @company = Company.find(params[:company_id])
            @worker.company = @company        
        end        

        
        def update
            @company = Company.find(params[:company_id])
            @worker.company = @company
            
            if @worker.update(worker_params)
                redirect_to company_worker_path(@worker.id)
    
            else
                render 'edit'
            end
        end
        
        
        private
        def worker_params
            params.require(:worker).permit( :code, :first_name, :last_name, :emp_mode, :role, :email, :reporting_manager, :job_title, :exprerience, :tel, :status, :company_id)
        end
    end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [ :show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    #get all workers in this company to show as subset.Find company first
    @workers = @company.workers
  end

  # GET /companies/new
  def new
    @company = Company.new
    # 2.times {@company.workers.build}

  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the whitelist through.
    def company_params
      #params.require(:company).permit(:name, :code, :started_on, :address, :city, :country, worker_attributes: [ :first_name, :code, :worker_id])
      params.require(:company).permit(:name, :code, :started_on, :address, :city, :country, workers_attributes: Worker.attribute_names.map(&:to_sym).push(:_destroy))

    end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_action :set_worker, only: [:show, :edit, :update, :destroy]
  
  #To authorize user access to controller’s actions, let’s add following to specific contoller:
  #load_and_authorize_resource


  # GET /workers
  # GET /workers.json
  def index
    @workers = Worker.all
  end

  # GET /workers/1
  # GET /workers/1.json
  def show
   @worker = Worker.find(params[:id])
   @salaries = @worker.salaries
  end

  # GET /workers/new
  def new
    @worker = Worker.new
  end

  # GET /workers/1/edit
  def edit
  end

  # POST /workers
  # POST /workers.json
  def create
    @worker = Worker.new(worker_params)

    respond_to do |format|
      if @worker.save
        format.html { redirect_to @worker, notice: 'Worker was successfully created.' }
        format.json { render :show, status: :created, location: @worker }
      else
        format.html { render :new }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workers/1
  # PATCH/PUT /workers/1.json
  def update
    respond_to do |format|
      if @worker.update(worker_params)
        format.html { redirect_to @worker, notice: 'Worker was successfully updated.' }
        format.json { render :show, status: :ok, location: @worker }
      else
        format.html { render :edit }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workers/1
  # DELETE /workers/1.json
  def destroy
    @worker.destroy
    respond_to do |format|
      format.html { redirect_to workers_url, notice: 'Worker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  
  def import
  #New method for import functionality
    Worker.import(params[:file])
    redirect_to workers_url, notice: 'Employees File was successfully uploaded.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_worker
      @worker = Worker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def worker_params
      params.require(:worker).permit(:code, :first_name, :last_name, :emp_mode, :role, :email, :reporting_manager, :job_title, :exprerience, :tel, :status, :company_id)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/companies/workers/_form.html.erb

<%= simple_form_for [@company, @worker] do |f| %>

  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

<h1>Recruit at <%= @company.name %></h1>

  <div class="form-inputs">
    <%= f.input :code %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :emp_mode %>
    <%= f.input :role %>
    <%= f.input :email %>
    <%= f.input :reporting_manager %>
    <%= f.input :job_title %>
    <%= f.input :exprerience %>
    <%= f.input :tel %>
    <%= f.input :status %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/companies/workers/index.html.erb


<h1>Employee List</h1>

<table >
  <thead>
    <tr>
      <th>Code</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Emp mode</th>
      <th>Role</th>
      <th>Email</th>
      <th>Reporting manager</th>
      <th>Job title</th>
      <th>Exprerience</th>
      <th>Tel</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @workers.each do |worker| %>
      <tr>
        <td><%= worker.code %></td>
        <td><%= worker.first_name %></td>
        <td><%= worker.last_name %></td>
        <td><%= worker.emp_mode %></td>
        <td><%= worker.role %></td>
        <td><%= worker.email %></td>
        <td><%= worker.reporting_manager %></td>
        <td><%= worker.job_title %></td>
        <td><%= worker.exprerience %></td>
        <td><%= worker.tel %></td>
        <td><%= worker.status %></td>
        <td><%= link_to 'Show', worker %></td>
        <td><%= link_to 'Edit', edit_worker_path(worker) %></td>
        <td><%= link_to 'Destroy', worker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_company_worker_path %>

app/views/companies/workers/new.html.erb


<h1>New Company Employee</h1>


<%= render 'form',partial: [@company,@worker] %>


<%= link_to 'Back', workers_path %>

app/views/companies/workers/show.html.erb
#redundant show

<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @worker.code %>
</p>

<p>
  <strong>First name:</strong>
  <%= @worker.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @worker.last_name %>
</p>

<p>
  <strong>Emp mode:</strong>
  <%= @worker.emp_mode %>
</p>

<p>
  <strong>Role:</strong>
  <%= @worker.role %>
</p>

<p>
  <strong>Email:</strong>
  <%= @worker.email %>
</p>

<p>
  <strong>Reporting manager:</strong>
  <%= @worker.reporting_manager %>
</p>

<p>
  <strong>Job title:</strong>
  <%= @worker.job_title %>
</p>

<p>
  <strong>Exprerience:</strong>
  <%= @worker.exprerience %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @worker.tel %>
</p>

<p>
  <strong>Status:</strong>
  <%= @worker.status %>
</p>

<table class="table table-striped table-hover " style="width:400px" >
  <thead>
     <tr>
           <th>Employee Slips</th>
           <th></th>
           <th></th>
           <th></th>
     </tr>
  </thead>
  <tbody>
    <% @salaries.each do |salary| %>
      <tr>
        <td><%= salary.salary %></td>
        <td><%= salary.nhif %></td>
        <td><%= link_to 'Destroy', salary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_worker_path(@worker) %> |
<%= link_to 'Back', workers_path %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @worker.code %>
</p>

<p>
  <strong>First name:</strong>
  <%= @worker.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @worker.last_name %>
</p>

<p>
  <strong>Emp mode:</strong>
  <%= @worker.emp_mode %>
</p>

<p>
  <strong>Role:</strong>
  <%= @worker.role %>
</p>

<p>
  <strong>Email:</strong>
  <%= @worker.email %>
</p>

<p>
  <strong>Reporting manager:</strong>
  <%= @worker.reporting_manager %>
</p>

<p>
  <strong>Job title:</strong>
  <%= @worker.job_title %>
</p>

<p>
  <strong>Exprerience:</strong>
  <%= @worker.exprerience %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @worker.tel %>
</p>

<p>
  <strong>Status:</strong>
  <%= @worker.status %>
</p>

<table class="table table-striped table-hover " style="width:400px" >
  <thead>
     <tr>
           <th>Employee Slips</th>
           <th></th>
           <th></th>
           <th></th>
     </tr>
  </thead>
  <tbody>
    <% @salaries.each do |salary| %>
      <tr>
        <td><%= salary.salary %></td>
        <td><%= salary.nhif %></td>
        <td><%= link_to 'Destroy', salary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_worker_path(@worker) %> |
<%= link_to 'Back', workers_path %>