config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  resources :roles
  devise_for :users

  resources :employees
  
  #gives route for import func
  resources :workers do
    collection { post :import }
  end
  
  resources :companies do
    resources :employees
  end
  
  resources :companies do
    resources :workers, controller: 'companies/workers'
  end
  
  get 'home/index'
  
  root to: 'home#index'
  
  resources :salaries

  resources :workers do
    resources :payslips

  end
  
  get '/payslips', to: 'payslips#index', as: :payslips
  post '/payslips/multiple', to: 'payslips#show_multiple', as: :payslips_multiple
  get '/payslips/multiple', to: 'payslips#show_multiple', as: :payslips_export_csv
   

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
    before_action :set_employee, only:[ :show, :edit, :update, :destroy]


    # If you are using custom generated devise controllers, you have to set routes in config/routes.rb:
    #      devise_for :users, controllers: {
    #      sessions: 'users/sessions',
    #      passwords: 'users/passwords',
    #      registrations: 'users/registrations'
    #  }
  
    def index
        @employees = Employee.all
    end
    

    def show
        @employee = Employee.find(params[:id])
    end
    
    def new
        @employee = Employee.new
    end
    

    def create
        @employee = Employee.new(employee_params)
        respond_to do |format|
            if @employee.save
                format.html {redirect_to @company, notice: 'Employee was created successfuly'}
                format.json{render :show, status: :created, location: @employee}
            else
                format.html{render :new}
                format.json { render json: :employee.errors, status: :unprocessable_entity }

            end
        end
    end



    def update
        respond_to do |format|
            if @employee.update(employee_params)
            format.html{redirect_to @employee, notice: 'Employee was successfully updated.'}
            format.json{render :show, status: :ok, location: @employee}
            else
              format.html{redirect_to @employee, notice: 'Employee was successfully updated.'}
              format.json{render :show, status: :ok, location: @employee}
            end
        end
    end
    
    def destroy
        @employee.destroy
        respond_to do |format|
            format.html{redirect_to employees_url, notice: 'Employee was successfully destroyed'}
            format.json{head "no_content"}
        end
    end
 
 
    private
    
    def set_employee
        @employee = Employee.find(params[:id])
    end
    
    #nevertrust the scary internet
    def employee_params
        params.require(:employee).permit(:firstname, :code, :nationalid, :company_id)
    end

end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb

<%= simple_form_for(@employee) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :firstname %>
    <%= f.input :code %>
    <%= f.input :nationalid %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb


<h1>Employees</h1>

<table>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Code</th>
      <th>National ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.firstname %></td>
        <td><%= employee.code %></td>
        <td><%= employee.nationalid %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New Employees</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb

<p>
  <strong>Firstname</strong>
  <%= @employee.firstname %>
</p>

<p>
  <strong>Code</strong>
  <%= @employee.codes %>
</p>

<p>
  <strong>National ID</strong>
  <%= @employee.nationalid %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employee_path %>