config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  resources :roles
  devise_for :users

  resources :employees
  
  #gives route for import func
  resources :workers do
    collection { post :import }
  end
  
  resources :companies do
    resources :employees
  end
  
  resources :companies do
    resources :workers, controller: 'companies/workers'
  end
  
  get 'home/index'
  
  root to: 'home#index'
  
  resources :salaries

  resources :workers do
    resources :payslips

  end
  
  get '/payslips', to: 'payslips#index', as: :payslips
  post '/payslips/multiple', to: 'payslips#show_multiple', as: :payslips_multiple
  get '/payslips/multiple', to: 'payslips#show_multiple', as: :payslips_export_csv
   

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
    has_many :workers, dependent: :destroy
    has_many :departments, :inverse_of => :company
    has_many :employments, through: :workers
    has_many :paychecks, through: :workers
    
    accepts_nested_attributes_for :workers, reject_if: all.blank?,
                                allow_destroy: true
    
end

app/controllers/companies/workers_controller.rb
module Companies

#disregard index,show and destroy method in routes since we in context of a client

    class WorkersController < ApplicationController
    
        def index
            @workers = Worker.all
        end
        
       def show
            @company = Company.find(params[:company_id])
            @worker = worker.find(params[:worker_id])
            @worker.company = @company
        end
        
        def new
            @company = Company.find(params[:company_id])
            @worker = Worker.new
        end
        
        def create
            @worker = Worker.new(worker_params)
            @company = Company.find(params[:company_id])
            @worker.company = @company
            
            
            if @worker.save(worker_params)
                redirect_to worker_path(@worker.id)
            else
                render 'new'
            end
            
        end
        
        def edit
            @company = Company.find(params[:company_id])
            @worker.company = @company        
        end        

        
        def update
            @company = Company.find(params[:company_id])
            @worker.company = @company
            
            if @worker.update(worker_params)
                redirect_to company_worker_path(@worker.id)
    
            else
                render 'edit'
            end
        end
        
        
        private
        def worker_params
            params.require(:worker).permit( :code, :first_name, :last_name, :emp_mode, :role, :email, :reporting_manager, :job_title, :exprerience, :tel, :status, :company_id)
        end
    end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [ :show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    #get all workers in this company to show as subset.Find company first
    @workers = @company.workers
  end

  # GET /companies/new
  def new
    @company = Company.new
    # 2.times {@company.workers.build}

  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the whitelist through.
    def company_params
      #params.require(:company).permit(:name, :code, :started_on, :address, :city, :country, worker_attributes: [ :first_name, :code, :worker_id])
      params.require(:company).permit(:name, :code, :started_on, :address, :city, :country, workers_attributes: Worker.attribute_names.map(&:to_sym).push(:_destroy))

    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_company_workers_list.html.erb



<table class="table table-striped table-hover ">
  <thead  >
    <tr>
      <th>Code</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Emp mode</th>
      <th>Role</th>
      <th>Email</th>
      <th>Reporting manager</th>
      <th>Job title</th>
      <th>Exprerience</th>
      <th>Tel</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% workers.each do |worker| %>
      <tr>
        <td><%= worker.code %></td>
        <td><%= worker.first_name %></td>
        <td><%= worker.last_name %></td>
        <td><%= worker.emp_mode %></td>
        <td><%= worker.role %></td>
        <td><%= worker.email %></td>
        <td><%= worker.reporting_manager %></td>
        <td><%= worker.job_title %></td>
        <td><%= worker.exprerience %></td>
        <td><%= worker.tel %></td>
        <td><%= worker.status %></td>
        <td><%= link_to 'Show', worker %></td>
        <td><%= link_to 'Edit', edit_worker_path(worker) %></td>
        <td><%= link_to 'Destroy', worker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Worker', new_company_worker_path(@company) , class: "btn btn-success" %>

<br>

<h3>Import Workers</h3>
<%= form_tag import_workers_path, multipart: true do %>
<%= file_field_tag :file %>
<%= submit_tag 'Upload Employees' %>
<% end %>

<hr>

app/views/companies/_form.html.erb
<%= simple_form_for(@company) do |f| %>

  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :city %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, 'Save Company' %>
  </div>
  <h3>Company Employees List</h3>

  <table class='table class="table table-striped table-hover'>
    <thead>
      <tr>
        <th></th>
      </tr>
    </thead>
    <tbody >
      <%= f.simple_fields_for :workers do |builder| %>
        <%= render 'worker_fields', f: builder %>
      <% end %>
    </tbody>

  </table>

  <div class="form-actions">


  </div>
<% end %>

app/views/companies/_worker_fields.html.erb
<table class="table table-striped table-hover ">
  <thead>
    <tr class="nested-fields">
      <th>#W</th>
    </tr>
  </thead>
  <tbody>
    <tr class="nested-fields">
      <td><%= link_to_remove_association "Delete Employe", f, class: 'btn btn-primary btn-sm' %></td>
      <td><%= f.input :code %></td>
      <td><%= f.input :first_name %></td>
      <td><%= f.input :emp_mode %></td>
      <td><%= f.input :last_name %></td>
      <td><%= f.input :role %></td>
    </tr>
    <tr class="nested-fields">
      <td><%= f.input :email %></td>
      <td><%= f.input :reporting_manager %></td>
      <td><%= f.input :job_title %></td>
      <td><%= f.input :exprerience %></td>
      <td><%= f.input :tel %></td>
      <td><%= f.input :status %></td>
    </tr>
  
  </tbody>
</table> 

</tr>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Companies</h1>

<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>Name</th>
      <th>Code</th>
      <th>Started on</th>
      <th>Address</th>
      <th>City</th>
      <th>Country</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.code %></td>
        <td><%= company.started_on %></td>
        <td><%= company.address %></td>
        <td><%= company.city %></td>
        <td><%= company.country %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Code:</strong>
  <%= @company.code %>
</p>

<p>
  <strong>Started on:</strong>
  <%= @company.started_on %>
</p>

<p>
  <strong>Address:</strong>
  <%= @company.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @company.city %>
</p>

<p>
  <strong>Country:</strong>
  <%= @company.country %>
</p>

<hr>

  <h5>Company Employees:</h5>
   <%=  render 'company_workers_list', workers:@workers %>



<%= link_to 'Edit', edit_company_path(@company), class: "btn btn-warning" %> |
<%= link_to 'Back', companies_path,class: "btn btn-warning" %>